name: carbonsense
description: Carbon Footprint calculator app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.3.beta <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: 4.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
