name: carbonsense
description: Carbon Footprint calculator app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.2.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
