List<String> kFunFacts = [
  "L'inquinamento atmosferico causato dalle emissioni di carbonio è uno dei principali fattori che contribuiscono al cambiamento climatico.",
  "L'impronta di carbonio rappresenta la quantità di gas serra emessi da un individuo, un'azienda o un'attività in un determinato periodo di tempo.",
  "Gli imballaggi di plastica sono responsabili di una significativa quantità di rifiuti che finiscono negli oceani.",
  "Le auto elettriche producono zero emissioni durante l'uso, contribuendo a ridurre l'inquinamento atmosferico.",
  "Il compostaggio dei rifiuti organici aiuta a ridurre la quantità di rifiuti che finisce nelle discariche.",
  "Le lampadine a LED consumano meno energia rispetto alle lampadine tradizionali, riducendo l'impronta di carbonio dell'illuminazione domestica.",
  "Il riciclo dell'alluminio richiede solo il 5% dell'energia necessaria per produrre alluminio da materie prime.",
  "Le auto ibride combinano un motore a combustione interna con un motore elettrico, riducendo le emissioni di gas serra.",
  "L'inquinamento acustico può causare disturbi del sonno, problemi di salute e stress.",
  "La deforestazione contribuisce all'aumento dell'impronta di carbonio poiché gli alberi assorbono anidride carbonica durante la fotosintesi.",
  "Il riciclo della carta riduce la quantità di alberi abbattuti per produrre nuova carta.",
  "L'inquinamento dell'aria può peggiorare le condizioni di salute delle persone con malattie respiratorie come l'asma.",
  "L'utilizzo del trasporto pubblico anziché dei veicoli privati può ridurre il traffico e le emissioni di carbonio.",
  "Il riciclo del vetro aiuta a conservare le risorse naturali e a ridurre l'impatto ambientale della sua produzione.",
  "Il riscaldamento globale è in gran parte causato dall'aumento delle emissioni di gas serra, come anidride carbonica e metano.",
  "La plastica monouso impiega centinaia di anni per degradarsi nell'ambiente.",
  "Il riciclo dell'acciaio riduce il consumo di energia e le emissioni di carbonio rispetto alla produzione di acciaio vergine.",
  "L'inquinamento idrico causato da sostanze chimiche e rifiuti può minacciare la vita acquatica e la salute umana.",
  "L'energia solare è una fonte rinnovabile che può ridurre l'impronta di carbonio e la dipendenza dai combustibili fossili.",
  "Il riciclo dei prodotti elettronici riduce l'estrazione di risorse naturali e previene l'inquinamento causato dai rifiuti elettronici.",
  "La produzione di carne e l'allevamento intensivo di bestiame sono responsabili di una significativa quantità di emissioni di metano, un potente gas serra.",
  "La riduzione dei rifiuti alimentari può contribuire a ridurre l'impronta di carbonio e la pressione sulle risorse naturali.",
];
