name: Build
on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build APK
        uses: marketplace-actions/builds-build-flutter-apk-and-create-github-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
